// Mock fixtures standing in for Supabase tables until the real database is
// connected (see SETUP_TODO.md). Shapes match lib/types.ts exactly so swapping
// these for real queries later is a drop-in change, not a rewrite.

import type {
  Restaurant,
  MenuCategory,
  MenuItem,
  Order,
  AnalyticsSnapshot,
  Driver,
  Subscription,
  StaffUser,
} from "./types";

export const restaurants: Restaurant[] = [
  {
    id: "r-fastfood",
    name: "Burger House",
    slug: "burger-house",
    type: "fast-food",
    templateId: "fast-food",
    tagline: "Beirut's favorite late-night burger stop",
    logoInitial: "B",
    currency: "USD",
    showBothCurrencies: true,
    lbpExchangeRate: 89500,
    languages: ["en", "ar"],
    hours: [
      { day: "mon", open: "11:00", close: "23:30" },
      { day: "tue", open: "11:00", close: "23:30" },
      { day: "wed", open: "11:00", close: "23:30" },
      { day: "thu", open: "11:00", close: "00:30" },
      { day: "fri", open: "11:00", close: "01:30" },
      { day: "sat", open: "11:00", close: "01:30" },
      { day: "sun", open: "12:00", close: "23:00" },
    ],
    planId: "basic",
    status: "active",
    whatsappNumber: "+96170123456",
    phone: "+96170123456",
    address: "Hamra Street, Beirut",
    posPrinterEnabled: true,
    kitchenPrinterEnabled: true,
    barPrinterEnabled: false,
    brandPalette: "template-default",
    temporarilyClosed: false,
  },
  {
    id: "r-bakery",
    name: "Sweet Crumbs Bakery",
    slug: "sweet-crumbs",
    type: "bakery",
    templateId: "bakery",
    tagline: "Fresh from our oven to your table, every morning",
    logoInitial: "S",
    currency: "USD",
    showBothCurrencies: true,
    lbpExchangeRate: 89500,
    languages: ["en", "ar", "fr"],
    hours: [
      { day: "mon", open: "07:00", close: "19:00" },
      { day: "tue", open: "07:00", close: "19:00" },
      { day: "wed", open: "07:00", close: "19:00" },
      { day: "thu", open: "07:00", close: "19:00" },
      { day: "fri", open: "07:00", close: "19:00" },
      { day: "sat", open: "08:00", close: "20:00" },
      { day: "sun", open: "08:00", close: "15:00" },
    ],
    planId: "free",
    status: "trial",
    whatsappNumber: "+96176234567",
    phone: "+96176234567",
    address: "Jounieh Highway, Mount Lebanon",
    posPrinterEnabled: true,
    kitchenPrinterEnabled: true,
    barPrinterEnabled: false,
    brandPalette: "template-default",
    temporarilyClosed: false,
  },
  {
    id: "r-finedining",
    name: "Le Jardin",
    slug: "le-jardin",
    type: "fine-dining",
    templateId: "fine-dining",
    tagline: "Contemporary Lebanese fine dining",
    logoInitial: "J",
    currency: "USD",
    showBothCurrencies: false,
    lbpExchangeRate: 89500,
    languages: ["en", "fr"],
    hours: [
      { day: "tue", open: "18:00", close: "23:30" },
      { day: "wed", open: "18:00", close: "23:30" },
      { day: "thu", open: "18:00", close: "23:30" },
      { day: "fri", open: "13:00", close: "00:00" },
      { day: "sat", open: "13:00", close: "00:00" },
      { day: "sun", open: "13:00", close: "22:00" },
      { day: "mon", open: "", close: "", closed: true },
    ],
    planId: "pro",
    status: "active",
    whatsappNumber: "+96181345678",
    phone: "+96181345678",
    address: "Downtown, Beirut",
    posPrinterEnabled: true,
    kitchenPrinterEnabled: true,
    barPrinterEnabled: false,
    brandPalette: "template-default",
    temporarilyClosed: false,
  },
  {
    id: "r-cafe",
    name: "Café Terra",
    slug: "cafe-terra",
    type: "cafe",
    templateId: "cafe",
    tagline: "Slow mornings, good coffee, warm pastries",
    logoInitial: "T",
    currency: "USD",
    showBothCurrencies: true,
    lbpExchangeRate: 89500,
    languages: ["en", "ar"],
    hours: [
      { day: "mon", open: "08:00", close: "20:00" },
      { day: "tue", open: "08:00", close: "20:00" },
      { day: "wed", open: "08:00", close: "20:00" },
      { day: "thu", open: "08:00", close: "20:00" },
      { day: "fri", open: "08:00", close: "22:00" },
      { day: "sat", open: "09:00", close: "22:00" },
      { day: "sun", open: "09:00", close: "20:00" },
    ],
    planId: "basic",
    status: "active",
    whatsappNumber: "+96178456789",
    phone: "+96178456789",
    address: "Gemmayze, Beirut",
    posPrinterEnabled: true,
    kitchenPrinterEnabled: true,
    barPrinterEnabled: false,
    brandPalette: "template-default",
    temporarilyClosed: false,
  },
];

export const subscriptions: Subscription[] = [
  {
    id: "sub-fastfood",
    restaurantId: "r-fastfood",
    periodStart: "2026-07-15",
    periodEnd: "2026-08-15",
    paymentProofRef: "OMT ref #48213",
  },
  {
    id: "sub-bakery",
    restaurantId: "r-bakery",
    periodStart: "2026-07-01",
    periodEnd: "2026-08-01",
  },
  {
    id: "sub-finedining",
    restaurantId: "r-finedining",
    periodStart: "2026-07-01",
    periodEnd: "2026-08-01",
    paymentProofRef: "Whish Money ref #77410",
  },
  {
    id: "sub-cafe",
    restaurantId: "r-cafe",
    periodStart: "2026-07-20",
    periodEnd: "2026-08-20",
  },
];

export const staffUsers: StaffUser[] = [
  { id: "st-fastfood-owner", restaurantId: "r-fastfood", name: "Rami Abou Chacra", phone: "+96170123456", role: "owner" },
  { id: "st-fastfood-1", restaurantId: "r-fastfood", name: "Nadine Fares", phone: "+96171112233", role: "staff" },
  { id: "st-fastfood-2", restaurantId: "r-fastfood", name: "Karim Haddad", phone: "+96176334455", role: "staff" },
  { id: "st-bakery-owner", restaurantId: "r-bakery", name: "Sara Khalil", phone: "+96176234567", role: "owner" },
  { id: "st-finedining-owner", restaurantId: "r-finedining", name: "Jean Nassar", phone: "+96181345678", role: "owner" },
  { id: "st-finedining-1", restaurantId: "r-finedining", name: "Elie Matta", phone: "+96181556677", role: "staff" },
  { id: "st-cafe-owner", restaurantId: "r-cafe", name: "Tarek Younes", phone: "+96178456789", role: "owner" },
];

export const categories: MenuCategory[] = [
  // Burger House
  { id: "c-burgers", restaurantId: "r-fastfood", name: "Burgers", sortOrder: 1 },
  { id: "c-sides", restaurantId: "r-fastfood", name: "Sides & Snacks", sortOrder: 2 },
  { id: "c-drinks-ff", restaurantId: "r-fastfood", name: "Drinks", sortOrder: 3 },
  // Sweet Crumbs
  { id: "c-cakes", restaurantId: "r-bakery", name: "Cakes", sortOrder: 1 },
  { id: "c-pastries", restaurantId: "r-bakery", name: "Pastries", sortOrder: 2 },
  { id: "c-bread", restaurantId: "r-bakery", name: "Fresh Bread", sortOrder: 3 },
  // Le Jardin
  { id: "c-starters", restaurantId: "r-finedining", name: "Starters", sortOrder: 1 },
  { id: "c-mains", restaurantId: "r-finedining", name: "Main Courses", sortOrder: 2 },
  { id: "c-desserts", restaurantId: "r-finedining", name: "Desserts", sortOrder: 3 },
  // Café Terra
  { id: "c-coffee", restaurantId: "r-cafe", name: "Coffee", sortOrder: 1 },
  { id: "c-food", restaurantId: "r-cafe", name: "Light Bites", sortOrder: 2 },
  { id: "c-pastries-cafe", restaurantId: "r-cafe", name: "Pastries", sortOrder: 3 },
];

export const menuItems: MenuItem[] = [
  // Burger House
  {
    id: "i-classic-burger",
    categoryId: "c-burgers",
    title: "Classic Smash Burger",
    description: "Beef patty, cheddar, pickles, house sauce, brioche bun.",
    price: 6.5,
    imageUrl: null,
    isAvailable: true,
    addons: [
      { id: "a-extra-cheese", name: "Extra cheese", extraPrice: 0.75 },
      { id: "a-bacon", name: "Add bacon", extraPrice: 1.5 },
    ],
    isPopular: true,
  },
  {
    id: "i-double-burger",
    categoryId: "c-burgers",
    title: "Double Trouble",
    description: "Two beef patties, double cheddar, caramelized onions.",
    price: 9,
    imageUrl: null,
    isAvailable: true,
    addons: [{ id: "a-bacon2", name: "Add bacon", extraPrice: 1.5 }],
  },
  {
    id: "i-chicken-burger",
    categoryId: "c-burgers",
    title: "Crispy Chicken Burger",
    description: "Fried chicken thigh, slaw, spicy mayo.",
    price: 7,
    imageUrl: null,
    isAvailable: false,
    addons: [],
  },
  {
    id: "i-fries",
    categoryId: "c-sides",
    title: "Golden Fries",
    description: "Crispy shoestring fries, house seasoning.",
    price: 3,
    imageUrl: null,
    isAvailable: true,
    addons: [{ id: "a-cheese-sauce", name: "Cheese sauce dip", extraPrice: 1 }],
    isPopular: true,
  },
  {
    id: "i-lunch-combo",
    categoryId: "c-sides",
    title: "Lunch Combo (12–3pm only)",
    description: "Burger + fries + drink at a lunch-hour price.",
    price: 8,
    imageUrl: null,
    isAvailable: true,
    availableFrom: "12:00",
    availableUntil: "15:00",
    addons: [],
  },
  {
    id: "i-cola",
    categoryId: "c-drinks-ff",
    title: "Soft Drink",
    description: "Can, 330ml.",
    price: 1.5,
    imageUrl: null,
    isAvailable: true,
    addons: [],
    variants: ["Cola", "Lemon-lime", "Orange"],
  },

  // Sweet Crumbs
  {
    id: "i-chocolate-cake",
    categoryId: "c-cakes",
    title: "Chocolate Layer Cake",
    description: "Rich Belgian chocolate, ganache, per slice.",
    price: 5,
    imageUrl: null,
    isAvailable: true,
    addons: [],
    isPopular: true,
  },
  {
    id: "i-cheesecake",
    categoryId: "c-cakes",
    title: "New York Cheesecake",
    description: "Classic baked cheesecake, berry compote.",
    price: 5.5,
    imageUrl: null,
    isAvailable: true,
    addons: [],
  },
  {
    id: "i-croissant",
    categoryId: "c-pastries",
    title: "Butter Croissant",
    description: "Laminated French-style croissant, baked fresh daily.",
    price: 2,
    imageUrl: null,
    isAvailable: true,
    addons: [],
    isPopular: true,
  },
  {
    id: "i-manoushe",
    categoryId: "c-pastries",
    title: "Cheese Manoushe",
    description: "Traditional Lebanese flatbread with akkawi cheese.",
    price: 3,
    imageUrl: null,
    isAvailable: true,
    addons: [{ id: "a-zaatar", name: "Add zaatar", extraPrice: 0.5 }],
  },
  {
    id: "i-baguette",
    categoryId: "c-bread",
    title: "Sourdough Loaf",
    description: "48-hour fermented sourdough, baked daily.",
    price: 4,
    imageUrl: null,
    isAvailable: false,
    addons: [],
  },

  // Le Jardin
  {
    id: "i-tartare",
    categoryId: "c-starters",
    title: "Beef Tartare",
    description: "Hand-cut beef, egg yolk, capers, sourdough crisp.",
    price: 16,
    imageUrl: null,
    isAvailable: true,
    addons: [],
  },
  {
    id: "i-scallops",
    categoryId: "c-starters",
    title: "Seared Scallops",
    description: "Cauliflower purée, brown butter, chive oil.",
    price: 18,
    imageUrl: null,
    isAvailable: true,
    addons: [],
    isPopular: true,
  },
  {
    id: "i-steak",
    categoryId: "c-mains",
    title: "Dry-Aged Sirloin",
    description: "28-day dry-aged, roasted bone marrow, red wine jus.",
    price: 34,
    imageUrl: null,
    isAvailable: true,
    addons: [],
    isPopular: true,
  },
  {
    id: "i-seabass",
    categoryId: "c-mains",
    title: "Roasted Seabass",
    description: "Fennel, saffron beurre blanc, confit lemon.",
    price: 29,
    imageUrl: null,
    isAvailable: true,
    addons: [],
  },
  {
    id: "i-souffle",
    categoryId: "c-desserts",
    title: "Dark Chocolate Soufflé",
    description: "Molten centre, gold leaf, vanilla anglaise.",
    price: 12,
    imageUrl: null,
    isAvailable: true,
    addons: [],
  },

  // Café Terra
  {
    id: "i-cappuccino",
    categoryId: "c-coffee",
    title: "Cappuccino",
    description: "Double shot espresso, steamed milk, cocoa dust.",
    price: 3,
    imageUrl: null,
    isAvailable: true,
    addons: [{ id: "a-oatmilk", name: "Oat milk", extraPrice: 0.5 }],
    isPopular: true,
  },
  {
    id: "i-latte",
    categoryId: "c-coffee",
    title: "Vanilla Latte",
    description: "Espresso, house vanilla syrup, steamed milk.",
    price: 3.5,
    imageUrl: null,
    isAvailable: true,
    addons: [{ id: "a-oatmilk2", name: "Oat milk", extraPrice: 0.5 }],
  },
  {
    id: "i-avocado-toast",
    categoryId: "c-food",
    title: "Avocado Toast",
    description: "Sourdough, smashed avocado, chili flakes, feta.",
    price: 6,
    imageUrl: null,
    isAvailable: true,
    addons: [],
    isPopular: true,
  },
  {
    id: "i-almond-croissant",
    categoryId: "c-pastries-cafe",
    title: "Almond Croissant",
    description: "Filled and topped with almond cream, sliced almonds.",
    price: 2.75,
    imageUrl: null,
    isAvailable: true,
    addons: [],
  },
];

const driverJoe: Driver = { id: "d-1", name: "Jad K.", phone: "+96171987654" };

export const orders: Order[] = [
  {
    id: "o-1001",
    queueNumber: 12,
    restaurantId: "r-fastfood",
    customerName: "Nour A.",
    customerPhone: "+96170111222",
    orderType: "delivery",
    address: "Verdun, Beirut",
    items: [
      { itemId: "i-classic-burger", title: "Classic Smash Burger", quantity: 2, unitPrice: 6.5, addons: ["Extra cheese"] },
      { itemId: "i-fries", title: "Golden Fries", quantity: 1, unitPrice: 3, addons: [] },
    ],
    total: 16.75,
    currency: "USD",
    status: "preparing",
    driver: driverJoe,
    createdAt: "2026-08-06T11:42:00+03:00",
  },
  {
    id: "o-1002",
    queueNumber: 13,
    restaurantId: "r-fastfood",
    customerName: "Karim H.",
    customerPhone: "+96170333444",
    orderType: "pickup",
    items: [
      { itemId: "i-double-burger", title: "Double Trouble", quantity: 1, unitPrice: 9, addons: [] },
      { itemId: "i-cola", title: "Soft Drink", quantity: 1, unitPrice: 1.5, addons: ["Cola"] },
    ],
    total: 10.5,
    currency: "USD",
    status: "received",
    createdAt: "2026-08-06T11:47:00+03:00",
  },
  {
    id: "o-1003",
    queueNumber: 14,
    restaurantId: "r-fastfood",
    customerName: "Lea S.",
    customerPhone: "+96170555666",
    orderType: "table",
    tableNumber: "5",
    items: [{ itemId: "i-lunch-combo", title: "Lunch Combo (12–3pm only)", quantity: 1, unitPrice: 8, addons: [] }],
    total: 8,
    currency: "USD",
    status: "ready_for_pickup",
    createdAt: "2026-08-06T12:05:00+03:00",
  },
  {
    id: "o-1004",
    queueNumber: 15,
    restaurantId: "r-fastfood",
    customerName: "Elie R.",
    customerPhone: "+96170777888",
    orderType: "delivery",
    address: "Achrafieh, Beirut",
    items: [
      { itemId: "i-classic-burger", title: "Classic Smash Burger", quantity: 1, unitPrice: 6.5, addons: [] },
    ],
    total: 6.5,
    currency: "USD",
    status: "out_for_delivery",
    driver: driverJoe,
    createdAt: "2026-08-06T12:10:00+03:00",
  },
  {
    id: "o-1005",
    queueNumber: 11,
    restaurantId: "r-fastfood",
    customerName: "Maya D.",
    customerPhone: "+96170999000",
    orderType: "pickup",
    items: [{ itemId: "i-fries", title: "Golden Fries", quantity: 2, unitPrice: 3, addons: [] }],
    total: 6,
    currency: "USD",
    status: "completed",
    createdAt: "2026-08-06T11:20:00+03:00",
  },
];

export const analytics: AnalyticsSnapshot = {
  ordersToday: 24,
  ordersThisWeek: 168,
  totalSalesToday: 312.5,
  totalSalesThisWeek: 2190,
  currency: "USD",
  topItems: [
    { title: "Classic Smash Burger", count: 58 },
    { title: "Golden Fries", count: 47 },
    { title: "Double Trouble", count: 33 },
    { title: "Soft Drink", count: 29 },
    { title: "Lunch Combo", count: 21 },
  ],
  salesTrend: [
    { date: "Mon", sales: 260 },
    { date: "Tue", sales: 305 },
    { date: "Wed", sales: 288 },
    { date: "Thu", sales: 340 },
    { date: "Fri", sales: 410 },
    { date: "Sat", sales: 465 },
    { date: "Sun", sales: 312 },
  ],
  peakHours: [
    { hour: "11am", orders: 8 },
    { hour: "12pm", orders: 22 },
    { hour: "1pm", orders: 19 },
    { hour: "6pm", orders: 14 },
    { hour: "7pm", orders: 27 },
    { hour: "8pm", orders: 31 },
    { hour: "9pm", orders: 24 },
    { hour: "10pm", orders: 12 },
  ],
};

export function getRestaurantBySlug(slug: string) {
  return restaurants.find((r) => r.slug === slug);
}

export function getCategoriesForRestaurant(restaurantId: string) {
  return categories
    .filter((c) => c.restaurantId === restaurantId)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getItemsForCategory(categoryId: string) {
  return menuItems.filter((i) => i.categoryId === categoryId);
}
